// Mock database layer - replace with actual MongoDB/Supabase in production
import type { User, Product, Order, Coupon, Banner } from "./types"

// Mock data storage
const users: User[] = []
let products: Product[] = []
const orders: Order[] = []
const coupons: Coupon[] = []
let banners: Banner[] = []

// Initialize with sample data
export function initializeDatabase() {
  products = [
    // Prawns & Shrimp
    {
      id: "1",
      name: "Medium Prawns - Cleaned",
      description: "Fresh, medium-sized prawns, cleaned and ready to cook. Perfect for curries and stir-fries.",
      category: "prawn",
      price: 450,
      weight: "500g",
      cut: "cleaned",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 50,
      rating: 4.8,
      reviews: [],
      nutrition: { protein: "24g", fat: "0.3g", carbs: "0g", calories: "99", omega3: "0.3g" },
      origin: "Coastal India",
      tags: ["bestseller", "fresh"],
      discount: 10,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "2",
      name: "Large Tiger Prawns",
      description: "Premium large tiger prawns with distinctive stripes. Ideal for grilling and special occasions.",
      category: "prawn",
      price: 650,
      weight: "500g",
      cut: "whole",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 35,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "26g", fat: "0.4g", carbs: "0g", calories: "105", omega3: "0.4g" },
      origin: "Coastal India",
      tags: ["premium", "bestseller"],
      discount: 15,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "3",
      name: "Small Freshwater Prawns",
      description: "Delicate small prawns perfect for light dishes and appetizers.",
      category: "prawn",
      price: 320,
      weight: "500g",
      cut: "cleaned",
      image: "/small-freshwater-prawns-cleaned.jpg",
      images: ["/small-freshwater-prawns-cleaned.jpg"],
      stock: 60,
      rating: 4.6,
      reviews: [],
      nutrition: { protein: "22g", fat: "0.2g", carbs: "0g", calories: "95", omega3: "0.2g" },
      origin: "Freshwater Farms",
      tags: ["fresh", "light"],
      discount: 5,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "4",
      name: "Jumbo King Prawns",
      description: "Extra-large king prawns, perfect for special celebrations and premium dishes.",
      category: "prawn",
      price: 850,
      weight: "500g",
      cut: "whole",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 25,
      rating: 5.0,
      reviews: [],
      nutrition: { protein: "28g", fat: "0.5g", carbs: "0g", calories: "110", omega3: "0.5g" },
      origin: "Premium Coastal",
      tags: ["premium", "luxury"],
      discount: 20,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Fish
    {
      id: "5",
      name: "Rohu Fish - Bengali Cut",
      description: "Traditional Bengali cut rohu fish, perfect for curries and traditional recipes.",
      category: "fish",
      price: 280,
      weight: "1kg",
      cut: "bengali",
      image: "/fresh-rohu-fish-bengali-cut.jpg",
      images: ["/fresh-rohu-fish-bengali-cut.jpg"],
      stock: 45,
      rating: 4.7,
      reviews: [],
      nutrition: { protein: "20g", fat: "5g", carbs: "0g", calories: "130", omega3: "0.8g" },
      origin: "Freshwater",
      tags: ["bestseller", "traditional"],
      discount: 8,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "6",
      name: "Mackerel Fish - Whole Cleaned",
      description: "Fresh mackerel fish, whole and cleaned. Rich in omega-3 fatty acids.",
      category: "fish",
      price: 320,
      weight: "1kg",
      cut: "whole",
      image: "/fresh-mackerel-fish-whole-cleaned.jpg",
      images: ["/fresh-mackerel-fish-whole-cleaned.jpg"],
      stock: 40,
      rating: 4.8,
      reviews: [],
      nutrition: { protein: "22g", fat: "12g", carbs: "0g", calories: "200", omega3: "2.5g" },
      origin: "Arabian Sea",
      tags: ["healthy", "omega3"],
      discount: 12,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "7",
      name: "Catla Fish - Bengali Cut",
      description: "Premium catla fish with Bengali cut, ideal for traditional Indian cooking.",
      category: "fish",
      price: 350,
      weight: "1kg",
      cut: "bengali",
      image: "/fresh-catla-fish-bengali-cut.jpg",
      images: ["/fresh-catla-fish-bengali-cut.jpg"],
      stock: 38,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "21g", fat: "6g", carbs: "0g", calories: "140", omega3: "0.9g" },
      origin: "Freshwater",
      tags: ["premium", "traditional"],
      discount: 10,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "8",
      name: "Pomfret Fish - Whole",
      description: "Delicate pomfret fish, perfect for grilling and pan-frying.",
      category: "fish",
      price: 420,
      weight: "1kg",
      cut: "whole",
      image: "/fresh-mackerel-fish-whole-cleaned.jpg",
      images: ["/fresh-mackerel-fish-whole-cleaned.jpg"],
      stock: 32,
      rating: 4.8,
      reviews: [],
      nutrition: { protein: "23g", fat: "4g", carbs: "0g", calories: "125", omega3: "0.7g" },
      origin: "Arabian Sea",
      tags: ["delicate", "premium"],
      discount: 15,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "9",
      name: "Salmon Fillet",
      description: "Premium Norwegian salmon fillets, rich in omega-3 and perfect for healthy meals.",
      category: "fish",
      price: 580,
      weight: "500g",
      cut: "fillet",
      image: "/fresh-mackerel-fish-whole-cleaned.jpg",
      images: ["/fresh-mackerel-fish-whole-cleaned.jpg"],
      stock: 28,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "25g", fat: "13g", carbs: "0g", calories: "210", omega3: "2.8g" },
      origin: "Norway",
      tags: ["premium", "healthy", "imported"],
      discount: 18,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "10",
      name: "Surmai Fish - Steaks",
      description: "King fish steaks, meaty and perfect for grilling and frying.",
      category: "fish",
      price: 480,
      weight: "1kg",
      cut: "steaks",
      image: "/fresh-rohu-fish-bengali-cut.jpg",
      images: ["/fresh-rohu-fish-bengali-cut.jpg"],
      stock: 35,
      rating: 4.7,
      reviews: [],
      nutrition: { protein: "24g", fat: "8g", carbs: "0g", calories: "170", omega3: "1.2g" },
      origin: "Arabian Sea",
      tags: ["meaty", "grilling"],
      discount: 12,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Squid & Cephalopods
    {
      id: "11",
      name: "Squid - Medium Cleaned",
      description: "Fresh medium squid, cleaned and ready to cook. Perfect for stir-fries and curries.",
      category: "squid",
      price: 380,
      weight: "500g",
      cut: "cleaned",
      image: "/fresh-cleaned-squid-medium.jpg",
      images: ["/fresh-cleaned-squid-medium.jpg"],
      stock: 42,
      rating: 4.6,
      reviews: [],
      nutrition: { protein: "18g", fat: "1g", carbs: "3g", calories: "92", omega3: "0.2g" },
      origin: "Arabian Sea",
      tags: ["fresh", "versatile"],
      discount: 8,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "12",
      name: "Squid Rings - Ready to Cook",
      description: "Pre-cut squid rings, ready for frying or grilling. Convenient and delicious.",
      category: "squid",
      price: 420,
      weight: "500g",
      cut: "rings",
      image: "/fresh-cleaned-squid-medium.jpg",
      images: ["/fresh-cleaned-squid-medium.jpg"],
      stock: 38,
      rating: 4.7,
      reviews: [],
      nutrition: { protein: "18g", fat: "1g", carbs: "3g", calories: "92", omega3: "0.2g" },
      origin: "Arabian Sea",
      tags: ["convenient", "ready-to-cook"],
      discount: 10,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "13",
      name: "Octopus - Whole",
      description: "Fresh whole octopus, tender and flavorful. Perfect for Mediterranean dishes.",
      category: "squid",
      price: 520,
      weight: "1kg",
      cut: "whole",
      image: "/fresh-cleaned-squid-medium.jpg",
      images: ["/fresh-cleaned-squid-medium.jpg"],
      stock: 20,
      rating: 4.8,
      reviews: [],
      nutrition: { protein: "19g", fat: "1.5g", carbs: "2g", calories: "95", omega3: "0.3g" },
      origin: "Arabian Sea",
      tags: ["premium", "mediterranean"],
      discount: 15,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Crabs
    {
      id: "14",
      name: "Blue Crab - Live",
      description: "Live blue crabs, fresh and active. Perfect for special occasions.",
      category: "crab",
      price: 680,
      weight: "1kg",
      cut: "whole",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 18,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "20g", fat: "2g", carbs: "0g", calories: "102", omega3: "0.4g" },
      origin: "Coastal India",
      tags: ["live", "premium"],
      discount: 20,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "15",
      name: "Mud Crab - Whole",
      description: "Premium mud crabs with sweet, tender meat. Ideal for special dishes.",
      category: "crab",
      price: 750,
      weight: "1kg",
      cut: "whole",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 15,
      rating: 5.0,
      reviews: [],
      nutrition: { protein: "21g", fat: "2.5g", carbs: "0g", calories: "108", omega3: "0.5g" },
      origin: "Coastal India",
      tags: ["premium", "luxury"],
      discount: 25,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "16",
      name: "Crab Meat - Cooked",
      description: "Pre-cooked crab meat, ready to use in salads, pasta, and other dishes.",
      category: "crab",
      price: 580,
      weight: "500g",
      cut: "meat",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 22,
      rating: 4.8,
      reviews: [],
      nutrition: { protein: "22g", fat: "2g", carbs: "0g", calories: "105", omega3: "0.4g" },
      origin: "Coastal India",
      tags: ["convenient", "cooked"],
      discount: 12,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Mussels & Shellfish
    {
      id: "17",
      name: "Green Mussels - Fresh",
      description: "Fresh green mussels, perfect for steaming, grilling, or pasta dishes.",
      category: "mussel",
      price: 320,
      weight: "1kg",
      cut: "whole",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 40,
      rating: 4.7,
      reviews: [],
      nutrition: { protein: "12g", fat: "2g", carbs: "7g", calories: "84", omega3: "0.5g" },
      origin: "Coastal India",
      tags: ["fresh", "versatile"],
      discount: 10,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "18",
      name: "Clams - Fresh",
      description: "Fresh clams with sweet meat, ideal for pasta, soups, and seafood platters.",
      category: "mussel",
      price: 380,
      weight: "1kg",
      cut: "whole",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 32,
      rating: 4.8,
      reviews: [],
      nutrition: { protein: "14g", fat: "1.5g", carbs: "5g", calories: "78", omega3: "0.4g" },
      origin: "Coastal India",
      tags: ["fresh", "premium"],
      discount: 12,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "19",
      name: "Oysters - Fresh",
      description: "Premium fresh oysters, perfect for raw consumption or grilling.",
      category: "mussel",
      price: 450,
      weight: "1kg",
      cut: "whole",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 25,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "9g", fat: "1.5g", carbs: "7g", calories: "68", omega3: "0.6g" },
      origin: "Coastal India",
      tags: ["premium", "luxury"],
      discount: 15,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Ready to Cook
    {
      id: "20",
      name: "Prawn Biryani Mix",
      description: "Pre-marinated prawns with spices, ready to cook biryani.",
      category: "ready-to-cook",
      price: 520,
      weight: "500g",
      cut: "marinated",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 30,
      rating: 4.8,
      reviews: [],
      nutrition: { protein: "24g", fat: "2g", carbs: "5g", calories: "130", omega3: "0.3g" },
      origin: "Coastal India",
      tags: ["ready-to-cook", "convenient"],
      discount: 15,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "21",
      name: "Fish Curry Mix",
      description: "Fresh fish pieces with curry spices, ready to cook.",
      category: "ready-to-cook",
      price: 380,
      weight: "500g",
      cut: "pieces",
      image: "/fresh-rohu-fish-bengali-cut.jpg",
      images: ["/fresh-rohu-fish-bengali-cut.jpg"],
      stock: 35,
      rating: 4.7,
      reviews: [],
      nutrition: { protein: "22g", fat: "3g", carbs: "4g", calories: "120", omega3: "0.8g" },
      origin: "Freshwater",
      tags: ["ready-to-cook", "traditional"],
      discount: 12,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "22",
      name: "Seafood Platter Mix",
      description: "Assorted seafood mix with prawns, fish, and squid. Perfect for special meals.",
      category: "ready-to-cook",
      price: 680,
      weight: "1kg",
      cut: "mixed",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 20,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "23g", fat: "2.5g", carbs: "3g", calories: "115", omega3: "0.6g" },
      origin: "Mixed",
      tags: ["ready-to-cook", "premium"],
      discount: 18,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Combos
    {
      id: "23",
      name: "Prawn & Fish Combo",
      description: "Perfect combination of medium prawns and fresh fish for a complete meal.",
      category: "combo",
      price: 750,
      weight: "1kg",
      cut: "mixed",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 25,
      rating: 4.8,
      reviews: [],
      nutrition: { protein: "23g", fat: "3g", carbs: "0g", calories: "120", omega3: "0.7g" },
      origin: "Mixed",
      tags: ["combo", "bestseller"],
      discount: 20,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "24",
      name: "Luxury Seafood Combo",
      description: "Premium selection with tiger prawns, salmon, and crab meat.",
      category: "combo",
      price: 1200,
      weight: "1.5kg",
      cut: "mixed",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 15,
      rating: 5.0,
      reviews: [],
      nutrition: { protein: "25g", fat: "5g", carbs: "0g", calories: "150", omega3: "1.2g" },
      origin: "Premium",
      tags: ["combo", "luxury", "premium"],
      discount: 25,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "25",
      name: "Budget Seafood Combo",
      description: "Great value combo with mixed fish and prawns for everyday cooking.",
      category: "combo",
      price: 520,
      weight: "1kg",
      cut: "mixed",
      image: "/fresh-rohu-fish-bengali-cut.jpg",
      images: ["/fresh-rohu-fish-bengali-cut.jpg"],
      stock: 40,
      rating: 4.6,
      reviews: [],
      nutrition: { protein: "22g", fat: "2.5g", carbs: "0g", calories: "110", omega3: "0.6g" },
      origin: "Mixed",
      tags: ["combo", "budget"],
      discount: 15,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Additional Fish Varieties
    {
      id: "26",
      name: "Hilsa Fish - Whole",
      description: "Premium hilsa fish, known for its delicate taste and tender meat.",
      category: "fish",
      price: 520,
      weight: "1kg",
      cut: "whole",
      image: "/fresh-rohu-fish-bengali-cut.jpg",
      images: ["/fresh-rohu-fish-bengali-cut.jpg"],
      stock: 28,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "21g", fat: "8g", carbs: "0g", calories: "160", omega3: "1.5g" },
      origin: "Freshwater",
      tags: ["premium", "traditional"],
      discount: 12,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "27",
      name: "Basa Fish - Fillets",
      description: "Mild and tender basa fish fillets, perfect for pan-frying and baking.",
      category: "fish",
      price: 280,
      weight: "500g",
      cut: "fillet",
      image: "/fresh-mackerel-fish-whole-cleaned.jpg",
      images: ["/fresh-mackerel-fish-whole-cleaned.jpg"],
      stock: 50,
      rating: 4.6,
      reviews: [],
      nutrition: { protein: "19g", fat: "3g", carbs: "0g", calories: "105", omega3: "0.3g" },
      origin: "Freshwater",
      tags: ["mild", "versatile"],
      discount: 8,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "28",
      name: "Tuna Steak",
      description: "Premium tuna steaks, perfect for grilling and searing.",
      category: "fish",
      price: 620,
      weight: "500g",
      cut: "steak",
      image: "/fresh-mackerel-fish-whole-cleaned.jpg",
      images: ["/fresh-mackerel-fish-whole-cleaned.jpg"],
      stock: 22,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "26g", fat: "1g", carbs: "0g", calories: "120", omega3: "0.3g" },
      origin: "Arabian Sea",
      tags: ["premium", "grilling"],
      discount: 15,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "29",
      name: "Cod Fish - Fillets",
      description: "Flaky white cod fish fillets, perfect for baking and frying.",
      category: "fish",
      price: 420,
      weight: "500g",
      cut: "fillet",
      image: "/fresh-mackerel-fish-whole-cleaned.jpg",
      images: ["/fresh-mackerel-fish-whole-cleaned.jpg"],
      stock: 35,
      rating: 4.7,
      reviews: [],
      nutrition: { protein: "20g", fat: "0.7g", carbs: "0g", calories: "82", omega3: "0.2g" },
      origin: "Imported",
      tags: ["imported", "healthy"],
      discount: 10,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Additional Prawns
    {
      id: "30",
      name: "Vannamei Prawns - Cleaned",
      description: "Premium vannamei prawns, larger and meatier than regular prawns.",
      category: "prawn",
      price: 520,
      weight: "500g",
      cut: "cleaned",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 32,
      rating: 4.8,
      reviews: [],
      nutrition: { protein: "25g", fat: "0.4g", carbs: "0g", calories: "102", omega3: "0.35g" },
      origin: "Aquaculture",
      tags: ["premium", "large"],
      discount: 12,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "31",
      name: "Scampi Prawns - Whole",
      description: "Delicate scampi prawns with sweet meat, perfect for special dishes.",
      category: "prawn",
      price: 680,
      weight: "500g",
      cut: "whole",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 20,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "24g", fat: "0.5g", carbs: "0g", calories: "100", omega3: "0.4g" },
      origin: "Mediterranean",
      tags: ["premium", "imported"],
      discount: 18,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "32",
      name: "Prawn Heads - For Broth",
      description: "Fresh prawn heads, perfect for making rich seafood broths and stocks.",
      category: "prawn",
      price: 150,
      weight: "500g",
      cut: "heads",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 60,
      rating: 4.5,
      reviews: [],
      nutrition: { protein: "8g", fat: "0.2g", carbs: "0g", calories: "35", omega3: "0.1g" },
      origin: "Coastal India",
      tags: ["budget", "broth"],
      discount: 5,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    // Specialty Items
    {
      id: "33",
      name: "Lobster Tail - Premium",
      description: "Premium lobster tails, perfect for special occasions and fine dining.",
      category: "specialty",
      price: 1500,
      weight: "500g",
      cut: "tail",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 10,
      rating: 5.0,
      reviews: [],
      nutrition: { protein: "27g", fat: "1g", carbs: "0g", calories: "105", omega3: "0.5g" },
      origin: "Imported",
      tags: ["luxury", "premium", "imported"],
      discount: 20,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "34",
      name: "Sea Urchin - Fresh",
      description: "Fresh sea urchin roe, a delicacy for sushi and fine dining.",
      category: "specialty",
      price: 980,
      weight: "200g",
      cut: "roe",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 8,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "14g", fat: "5g", carbs: "2g", calories: "105", omega3: "1.2g" },
      origin: "Imported",
      tags: ["luxury", "specialty"],
      discount: 15,
      isFeatured: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "35",
      name: "Scallops - Fresh",
      description: "Premium fresh scallops with sweet, tender meat. Perfect for grilling.",
      category: "specialty",
      price: 720,
      weight: "500g",
      cut: "whole",
      image: "/fresh-medium-prawns-on-wooden-board.jpg",
      images: ["/fresh-medium-prawns-on-wooden-board.jpg"],
      stock: 18,
      rating: 4.9,
      reviews: [],
      nutrition: { protein: "17g", fat: "1.5g", carbs: "3g", calories: "88", omega3: "0.3g" },
      origin: "Coastal India",
      tags: ["premium", "delicate"],
      discount: 12,
      isFeatured: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]

  coupons.push(
    {
      id: "1",
      code: "SEAFRESH10",
      discount: 10,
      discountType: "percentage",
      maxUses: 100,
      usedCount: 0,
      minOrderValue: 500,
      expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      isActive: true,
    },
    {
      id: "2",
      code: "WELCOME20",
      discount: 20,
      discountType: "percentage",
      maxUses: 50,
      usedCount: 0,
      minOrderValue: 1000,
      expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      isActive: true,
    },
  )

  banners = [
    {
      id: "1",
      title: "Fresh from the Ocean",
      subtitle: "Get 20% off on your first order",
      image: "/ocean-seafood-banner.jpg",
      link: "/shop",
      isActive: true,
      displayOrder: 1,
    },
  ]
}

// User operations
export async function createUser(userData: Partial<User>): Promise<User> {
  const user: User = {
    id: Math.random().toString(36).substr(2, 9),
    email: userData.email || "",
    phone: userData.phone || "",
    name: userData.name || "",
    role: userData.role || "customer",
    addresses: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  }
  users.push(user)
  return user
}

export async function getUserByEmail(email: string): Promise<User | null> {
  return users.find((u) => u.email === email) || null
}

export async function getUserById(id: string): Promise<User | null> {
  return users.find((u) => u.id === id) || null
}

// Product operations
export async function getAllProducts(): Promise<Product[]> {
  return products
}

export async function getProductById(id: string): Promise<Product | null> {
  return products.find((p) => p.id === id) || null
}

export async function getProductsByCategory(category: string): Promise<Product[]> {
  return products.filter((p) => p.category === category)
}

export async function searchProducts(query: string): Promise<Product[]> {
  const lowerQuery = query.toLowerCase()
  return products.filter(
    (p) => p.name.toLowerCase().includes(lowerQuery) || p.description.toLowerCase().includes(lowerQuery),
  )
}

// Order operations
export async function createOrder(orderData: Partial<Order>): Promise<Order> {
  const order: Order = {
    id: Math.random().toString(36).substr(2, 9),
    userId: orderData.userId || "",
    items: orderData.items || [],
    address: orderData.address || ({} as any),
    totalAmount: orderData.totalAmount || 0,
    subtotal: orderData.subtotal || 0,
    tax: orderData.tax || 0,
    discount: orderData.discount || 0,
    paymentMethod: orderData.paymentMethod || "cod",
    paymentStatus: "pending",
    orderStatus: "pending",
    deliveryDate: orderData.deliveryDate || new Date(),
    deliverySlot: orderData.deliverySlot || "",
    trackingNumber: `TRK${Date.now()}`,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
  orders.push(order)
  return order
}

export async function getOrdersByUserId(userId: string): Promise<Order[]> {
  return orders.filter((o) => o.userId === userId)
}

export async function getOrderById(id: string): Promise<Order | null> {
  return orders.find((o) => o.id === id) || null
}

export async function updateOrderStatus(orderId: string, status: Order["orderStatus"]): Promise<Order | null> {
  const order = orders.find((o) => o.id === orderId)
  if (order) {
    order.orderStatus = status
    order.updatedAt = new Date()
  }
  return order || null
}

// Coupon operations
export async function validateCoupon(code: string): Promise<Coupon | null> {
  const coupon = coupons.find((c) => c.code === code)
  if (coupon && coupon.usedCount < coupon.maxUses) {
    return coupon
  }
  return null
}

// Banner operations
export async function getActiveBanners(): Promise<Banner[]> {
  return banners.filter((b) => b.isActive).sort((a, b) => a.displayOrder - b.displayOrder)
}
